# Generated by Django 3.1.3 on 2020-12-21 08:27

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=511)),
                ('description', models.TextField(verbose_name=builtins.max)),
                ('image', models.ImageField(upload_to='', verbose_name=builtins.max)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
